// @generated by protoc-gen-connect-web v0.8.6 with parameter "target=ts"
// @generated from file proto/api.proto (package api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HealthCheckRequest, HealthCheckResponse, ProveRequest, ProveResponse, SetUpRequest, SetUpResponse, VerifyRequest, VerifyResponse } from "./api_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1.ZkMokuService
 */
export const ZkMokuService = {
  typeName: "api.v1.ZkMokuService",
  methods: {
    /**
     * @generated from rpc api.v1.ZkMokuService.HealthCheck
     */
    healthCheck: {
      name: "HealthCheck",
      I: HealthCheckRequest,
      O: HealthCheckResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.ZkMokuService.SetUp
     */
    setUp: {
      name: "SetUp",
      I: SetUpRequest,
      O: SetUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.ZkMokuService.Prove
     */
    prove: {
      name: "Prove",
      I: ProveRequest,
      O: ProveResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.ZkMokuService.Verify
     */
    verify: {
      name: "Verify",
      I: VerifyRequest,
      O: VerifyResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

